### ISSUE TITLE
[Question]: Running a watcher for tailwind on local development and hotreload not working?

### ISSUE THREAD

**Issue by Saveljeffjonatan** [dotsehyde/go-echo-templ#1]
Hey, I pulled this down and great job but I am missing 2 key parts. If I use air and run with templ files it re runs the build but I am still forced to do a browser refresh *F5 to see the changes.

I added a tailwind.config.js file but I still can't edit the styling.

**Comment by dotsehyde** [comment]
Alright,
1. Air only hot-reloads the server side, not the client side running in the browser
- I have updated the makefile (`included templ generate`) 

2. I already complied tailwindcss and imported from `/assets/css/`  since I only wanted to focus on how templ engine is used.

**Comment by Saveljeffjonatan** [comment]
Ah okay, do you know of a simple solution to deal with client update? Kinda like how hot-reloading in react works? 
Do you also have an example or know how to setup a watcher on tailwind changes?

Basically, I've been searching for a stack that uses:
Go
Echo
Templ
Tailwindcss

With hot-reload and full automated developer experience. Basically like a fullstack BE application like Elixir with Phoenix Liveview. Else my quesiton would be, how do people develop webapps with this stack if they have too recompile and run server command on every change all the time for webchanges? Seems like a incredibly annoying thing to have too do.

**Comment by dotsehyde** [comment]
Sorry, Golang is mainly for backend (server-side) development, so support for client hot-reload is not available to the best of my knowledge.

And yeah, This stack is called GOTHAM, learn more with this video:

- [GOTHAM Stack](https://www.youtube.com/watch?v=nSdVRhW8epY&pp=ygUPZ28gZ290aGFtIHN0YWNr)

It is fairly a new stack...

For tailwind watcher, 
- Use npx to init the tailwind configs
- Add `pre_cmd = ["npx tailwindcss build -o public/css/styles.css"]` to the air.toml (to compile tailwind before building)
👍
